version: '3.8'
services:
  blockchain:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - EXPRESS_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - blockchain-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - blockchain-network

networks:
  blockchain-network:
    driver: bridge
